# Generated by Django 4.1.4 on 2022-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('validity', models.IntegerField(choices=[(1, 'Day'), (7, 'Week'), (30, 'Month')], default=1)),
                ('sms', models.IntegerField(choices=[(0, 'Useless'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=0)),
                ('call', models.IntegerField(choices=[(0, 'Useless'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=0)),
                ('datas', models.IntegerField(choices=[(0, 'Useless'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=0)),
            ],
        ),
    ]
